### ISSUE TITLE
Adding screenshots and videos to Creative Works doesn't work

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#106]
When I click "Add new" or "Update Widget" in the Creative Works section for screenshots and videos, the page scrolls to the top of the entry and nothing else happens. Data already entered but not saved does not disappear.  
<img width="823" alt="Screen Shot 2020-09-04 at 14 35 49" src="https://user-images.githubusercontent.com/44365847/92239971-23329000-eebc-11ea-94a3-86a60dbc46e9.png">

**Comment by steinmb** [comment]
Unable to reproduce. Tested with Safari Version 13.1.2, Google Chrome Version 85.0.4183.83 and Firefox 80.0. Logged in as regular user.

**Comment by LindaKairus** [comment]
I have been adding to Creative Works, Machine Vision Situations and Characters all types of media; images, screenshots, videos and remote videos (vimeo, youtube), and it is working fine. There is no "Update Widget" button just add media.
So I think what ever was the problem is not there anymore and the issue can be closed.
<img width="904" alt="Screenshot 2020-09-21 at 11 18 00" src="https://user-images.githubusercontent.com/16516978/93751044-be39a280-fbfc-11ea-98a2-8d706e307f8c.png">
