### ISSUE TITLE
Fix characters

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#122]
With the new generic entity list, we also have to look at the characters. Here are a few issues that we need to look into:

- [x] Are [Workers](https://machine-vision.no/character/workers) important enough to capture the power balance/financial incentive to not label them as "Humans in general"? I lean towards yes, keeping it, but we should make an active choice.

- [x] Are these [Fans](https://machine-vision.no/character/fans) really "Humans in general"?

- [x] Is it important to capture the brevity of Race/ethnicity for these [Inhabitants](https://machine-vision.no/character/inhabitants) or are they "Humans in general"?

- [x] Make a group for Asian people or keep these two separate? [Citizens of Namie](https://machine-vision.no/character/citizens-namie) and [Tokyo population](https://machine-vision.no/character/tokyo-population).

- [x] Maybe an unknown [First person human narrator](https://machine-vision.no/character/first-person-human-narrator) is an Entity? There are a few in the database, now as distinct characters.

- [x] Are these the same? [Immigrant group](https://machine-vision.no/character/immigrant-group-persons-color) and [Refugees](https://machine-vision.no/character/refugees-incoming).

If there are more of these, add them below :)

**Comment by jilltxt** [comment]
Thanks for raising this question, @ragsol! I think it really depends on what we want to use Entities for in our analyses. I think these are likely the two most important areas we'll want to explore:

1. Power relationships - are corporations or states presented as controlling/oppressing humans in general, or characters with particular characteristics, such as immigrants or people of colour? 
2. In artworks in particular, the Creator and the Image are entities that are important but can't be captured in our other categories. So we need these to ask questions like "What do Technologies do with/to the Image? How is agency distributed between Creator, Technologies and Image?"

Can anyone think of other questions we would want to use Entities to answer?

I think all your questions relate to the first of these (power relationships). Here I actually **think we should keep "Humans in General" fairly strict** so we only use it when we really are referring to **either all humans or any human**. And of course, sticking to the _if there are two or more traits make a character_ rule. 

For our OTHER research questions I think that making specific characters for specific works is almost always going to better than making more generic characters. This is partly because it is better to keep the verbs with a specific character. 

For instance, the Refugees in Incoming are [Watched, Surveilled, Unaware](https://machine-vision.no/machine-vision-situation/incoming-thermal-imaging-refugees). The Immigrant Group in The Virtual Watchers is [Watched, Controlled](https://machine-vision.no/machine-vision-situation/virtual-watchers-surveilling-border). Hm, I suppose in this case there is a clear overlap, and maybe it wouldn't matter if they were logged as the same character. I just have this instinct to keep them separate. 

@mareinna, you also argued for separate characters for separate works yesterday - do you want to add anything here? Perhaps you have a clearer argumentation than I can muster right now!!

**Comment by jilltxt** [comment]
I am closing this. We'll leave as is.
