### ISSUE TITLE
Creative Works with 2 main genres - What to do?

### ISSUE THREAD

**Issue by LindaKairus** [jilltxt/machinevision#162]
There are 6 works that are tagged belonging to two of the main genres:

Lessons on Leaving Your Body (Art + Narrative) 
https://machine-vision.no/creative-work/lessons-leaving-your-body

AI, Ain't I A Woman (Art + Narrative) 
https://machine-vision.no/creative-work/ai-aint-i-woman

Big Brother Is Shaping You (Game + Narrative)
https://machine-vision.no/creative-work/big-brother-shaping-you

Tendar (Game + Narrative)
https://machine-vision.no/creative-work/tendar

The Argus Project (Art + Narrative) 
https://machine-vision.no/creative-work/argus-project

Emotion Hero (Art+Game)
https://machine-vision.no/creative-work/emotion-hero

This causes confusion e.g. 500 works but then adding Art, Games, Narratives 506 works. So if we keep it like this we need to remember to explain it. It also causes duplication in edges between verbs if not deleted manually when we have all the works together in a network viz. If we keep this we need to remember an extra step in cleaning the data for Gephi.

Question is if only 6 works is reason to keep them or should we just assign them to one main genre? Any opinions on that?

**Comment by jilltxt** [comment]
Lessons on Leaving Your Body (Art + Narrative)
https://machine-vision.no/creative-work/lessons-leaving-your-body
--> I have deleted Narrative, it's more a documentary anyway and is usually exhibited as art

AI, Ain't I A Woman (Art + Narrative)
https://machine-vision.no/creative-work/ai-aint-i-woman
--> I have deleted Narrative - similar to above.

Big Brother Is Shaping You (Game + Narrative)
https://machine-vision.no/creative-work/big-brother-shaping-you
--> I removed Narrative since Ragnhild entered this so I figure it's primarily a game.

Tendar (Game + Narrative)
https://machine-vision.no/creative-work/tendar
--> @ragsol - do you want to keep this as a game? I am happy to either delete Narrative or Game, don't mind which.

The Argus Project (Art + Narrative)
https://machine-vision.no/creative-work/argus-project
--> I have deleted Narrative

Emotion Hero (Art+Game)
https://machine-vision.no/creative-work/emotion-hero
--> @ragsol - opinions?

**Comment by jilltxt** [comment]
I think we simplify and remove the double genres. I've removed Narrative from all these. The only remaining question is Emotion Hero which is currently Art/Game. I think we should probably remove Art since it's part of Ragnhild's 77 game dataset - but I want to hear @ragsol's opinion first?

**Comment by LindaKairus** [comment]
We agreed on discord with @ragsol that Emotion Hero is a Game.

**Comment by jilltxt** [comment]
OK, then all these double-genre works are now resolved.

**Comment by jilltxt** [comment]
@ragsol If you want me to add a sentence to the description of Emotion Hero explaining that it's "two-part, being first the game (get the face right!) and then the results (uncovering the work behind the data collection)" can you write out a suitable sentence here and I'll add it? If not, please just close this issue!

**Comment by jilltxt** [comment]
I found a new double-genre entry: 

I Spy with my Machine Eye (art + narrative) 
https://machine-vision.no/creative-work/i-spy-my-machine-eye
--> This is a a sequence of short descriptions with illustrative photos taken by a drone. I'd like to keep as Narrative, as it works well as e-lit, but if it's useful to you, @LindaKairus, I'm happy for you to claim it as art.

**Comment by LindaKairus** [comment]
@jilltxt it is fine for me that this work is a narrative.

**Comment by jilltxt** [comment]
Great, done. I found one last work that was not tagged as Narrative, Art or Game, so we only had 499 works despite there being 500 works in the database.It was a Narrative so doesn't affect art or games. I fixed this so we'll have new exports.
