### ISSUE TITLE
Data export reveals Characters without data

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#166]
This post is for the taggers and not for the data export itself:

I had Excel show me null values, and there are quite a few Characters still without one or more traits. Here's the list and an example of how it looks:
![image](https://user-images.githubusercontent.com/49433732/146390037-f255c245-39e9-44aa-8788-82166406a781.png)
Fix or just acknowledge that we lack the info?

- [x] "Alan Walker"
- [x] "Lauren McCarthy"
- [x] "Mari Nagem"
- [x] Abigail Fort (Thoughts and Prayers)
- [x] Agent Everett Ross
- [x] Agents (sentient programs) *renamed Agent Smith and made an individual not group - I think it works better that way.*
- [x] Alex
- [x] Amazon Mechanical Turk worker (Lacework)
- [x] Amos Burton *Deleted, was not in any situation*
- [x] Andrea Farbe
- [x] Annotator (Suspicious Behavior)
- [x] Arthur (Best Friend)
- [x] Audience (Man With a Movie Camera)
- [x] audience (the last one) *Deleted - not used in any situation*
- [x] Balem Abrasax
- [x] Carlos Olivera *Deleted - not used in any situation*
- [x] Claire *Deleted - not used in any situation*
- [x] Concert audience (Song for a New Day)
- [x] crew (Six Wakes) *Deleted crew and put the entity Humans in general in the situation instead with the same verbs*
- [x] Dr. Brown *Deleted - not used in any situation*
- [x] Dweller of Alina's kentuki
- [x] Ellie *Deleted - was an unused duplicate*
- [x] Fredrik
- [x] Gamemasters (The Hunger Games)
- [x] Ghost in Breathe
- [x] Grigor
- [x] Haru (The Cat Returns)
- [x] Helena
- [x] Hundred Eyes
- [x] Jarvis
- [x] Julian Makowski (BouvetÃ¸ya 2052)
- [x] Lindy
- [x] Luce Cannon
- [x] Narrator (Exhalation)
- [x] Nikolina
- [x] Nocko
- [x] Nozomi
- [x] Palle Olsson
- [x] Peter B. Parker *Deleted - not in any situation*
- [x] Professor (Drones Don't Kill People)
- [x] Professor's Wife (Drones Don't Kill People)
- [x] Protagonist (Who*You)
- [x] Prowler
- [x] Psychologist (Cosmodrama)
- [x] Scavengers
- [x] SEER Robot
- [x] Sentinel (The Matrix) *Deleted - not used in any situation*
- [x] Sophia (Fall)
- [x] T'Chaka
- [x] Three high-school aged girls (The Fall) *group*
- [x] Virtual friends (Best friend) *group*
- [x] Walkers (Alan Walker fans) *group*
- [x] WeUs pillform technology *deleted as 
- [x] Wintermute
- [x] Workers (Outra 33 Bienal de SÃ£o Paulo)

**Comment by LindaKairus** [comment]
I thought I went all artwork characters through, but apparently I missed some. This would have been more effective check and clean before we closed the database. However, if Jill has the possibilities/time to change it here is the info for artwork characters.  However, if there is a decision not to leave it it is fine. Basically, they are missing because I forgot to choos Unknown/not applicable on all of them.

"Lauren McCarthy"
Sexuality:
Unknown/not applicable

"Mari Nagem"
Sexuality:
Unknown/not applicable

Amazon Mechanical Turk worker (Lacework)
Gender
Unknown/Not applicable
Race/ethnicity
Unknown/not applicable
Sexuality:
Unknown/not applicable

Annotator (Suspicious Behavior)
Sexuality:
Unknown/not applicable

SEER Robot
Sexuality:
Unknown/not applicable

Workers (Outra 33 Bienal de São Paulo)
Sexuality:
Unknown/not applicable

**Comment by jilltxt** [comment]
Thanks for pointing this out, @ragsol. I'm correcting some, and crossing off the list above as I do so. Many of these are "group" characters. We need to either NOT export them, or mark them clearly. 

Is anyone using group characters in analyses?

**Comment by jilltxt** [comment]
I fixed all listed characters with null values. There aren't many group characters, and I decided to just put Unknown for the fields where there are multiple genders or whatever in the group. I also added a brief explanation of this to the Data in Brief paper.
