### ISSUE TITLE
Should "user" be a separate character, and if so, one empty "user" for all instances, or individually defined users for different works?

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#36]
Create "user" (lower case!) as options in "Name" category.

_(Based on our definition of "If the user is a character, type user and select that option in the autocomplete")_

**Comment by ragsol** [comment]
Now I have filled in two "users" without an autofill/premade option, and they show up as two different characters with the same name. Their sentiments may be different, so they need be different, but perhaps we need to separate them more in the naming in order to find them in the drop-down menus? It is hard to pick between user, user, user and user :) Ideas?

**Comment by jilltxt** [comment]
We need to discuss this. I think we agreed to only have one "user" as the character, and to leave the content/sentiments of the user blank since they could be different depending on the actual flesh and blood human person playing the game. User=Ragnhild is creeped out by Just Dance, while Benji (aged 9) thinks its absolutely awesome and not at all creepy, for instance.

**Comment by ragsol** [comment]
I removed the "user" when we changed the  Characters and the Situations lists - June 20, 2019.

**Comment by jilltxt** [comment]
Is this completed in the database, or do I need to actually implement it?

**Comment by ragsol** [comment]
I think we just need to fix old entries, otherwise it should be fine.

**Comment by jilltxt** [comment]
User can be a Generic Entity in the new system. I added it to the help text.
