### ISSUE TITLE
Situations issues

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#37]
- [x] Operator/Viewed by: This category is doubled with "Characters" except these few bullet points:
_Not applicable An individual A targeted group Everyone Everything  Actual user/player/reader/viewer of work is also the protagonist_
Consider removing the overlaps to avoid carpal tunnel syndrome?

- [x] Consider adding "Real corporation" to separate between real and fiction? (e.g. _Pokémon Go_'s tech "Owner")

- [ ] Do we tag both "Everyone" and "Everything" when we want to include living and nonliving entities?

- [x] Consider "Real/existing corporation" to separate between reality and fiction, e.g. in _Pokémon Go_'s Niantic? 

- [ ] For how MV functions in a larger societal context: Consider "Playing" or "Entertaining" where we now resort to "Inspiring/motivating"?

- [ ] Should we add "What viewed" also? Not just "who". E..g Oceans eight when its a necklace being scanned.

- [ ] Are quotes needed on the front page when we also have them in the Situation? I feel the Situation ones are more important - general quotes w/o MV not so much

- [ ] Define "Everyone", "Everything" etc.

- [x] How do we tag for sentiment for person viewed when they don't know they're being viewed? "Neutral" seems wrong... Perhaps "Unaware"?

- [ ] This is the case in most object recognition MV-situations I would need a new tag in Who (or what) is viewed by the machine vision in this situation?: I have specific objects that are viewed. I is not everything, or everyone. I could use targeted group, but I always thought that is some kind of living/aware entities and not objects. (added by Linda)

- [ ] In What is the machine vision doing in this specific situation?: I would suggest the tag Organizing (e.g. Jller)(added by Linda)

**Comment by jilltxt** [comment]
I will:
- rephrase the question about owner/developer of technology to "referenced in the work"

**Comment by LinnHeidi** [comment]
Should we have as one of the options to owner/developer of technology: Unknown?
Use this tag when there is someone owning it, but its not specified? Not sure

**Comment by jilltxt** [comment]
I love the idea of adding Unaware. Also, I think we should just add "what" to the "who viewed". I'll go ahead and add these two things.

**Comment by jilltxt** [comment]
OK, adding unaware is much more complicated than I thought. We can't add "Unaware" as the system is now, because

1. It doesn't match the grammar of the question "Viewed person feels that machine vision is", because you're asking about what to do when the person being viewed doesn't know they're being watched, whereas what our coding schema now asks is what the person being viewed thinks about the machine vision. We would have to add a whole new sentence or something. Or perhaps a separate question altogether, in which case we would need to consider how useful that would be. 

2. The sentiment taxonomy is used various places, not just for viewed person, so adding "unaware" would mean we not only have unaware as an option here:
<img width="402" alt="Skjermbilde 2019-06-19 kl  10 12 49" src="https://user-images.githubusercontent.com/44365847/59748191-d8a70280-927a-11e9-94b3-bdcb6acc7345.png">

but also 

- General attitude towards machine vision (Machine Vision Situation)
- Operator feels that the machine vision is (Machine Vision Situation)
- Sentiment (in Creative Work)

So if we add "unaware" we need to think about whether it works in those places also. 

So I'm not sure what to do. Maybe just not tag for this at all? How important is it to know whether the person viewed knows they are being watched?

**Comment by jilltxt** [comment]
Aware:
Unaware: 
Partially aware: Some people may be aware, or people are aware that there is some machine vision, but not fully aware of the extent.

**Comment by jilltxt** [comment]
We remove sentiments from characters, because characters often have conflicting sentiments in different situations. This means that we will lose the possibility to differentiate between different sentimetns different characters have in a single situation, but that's OK. 

A disadvantage is that it's harder to analyse characters (e.g. black female cyborgs tend to haev a more hostile attitude to machine vision than white female humans), but this would be somewhat flawed data anyway, since individual charcters often have conflicting sentiments, e.g. Spider Jerusalem: the main character has very different attitudes to different kinds of machine vision (glasses vs maker). 

We discussed using the character entity for populations and Groups (the general population, migrants in a specific work etc) but decided against it because the sentiments aren't Connected to characters anymore, so sentimetns are always Connected to the situation.

I am hiding sentiments from characters, and we will test this for a day and reconsider.

**Comment by LinnHeidi** [comment]
Hi, I am just tagging Spiderman (please look over it) and I am wondering if we should have an extra option? If not viewed, than seeing. There are several situations where its not about being viewed but its simply observing/looking at the machine vision. See Spiderman (Deepfakes) and Iron Man (Augmented reality).

**Comment by LinnHeidi** [comment]
What should we tag when referring to hologram technology? AR, Image Generation, or own tag?

**Comment by mareinna** [comment]
What should we do when there are multiple separate characters operating or being viewed by the machine vision, that have contradictory/different experiences with the machine vision? 

(For example, if one character viewed by the MV experiences it as oppressive, the other experiences it as empowering.)

As it is now, when adding several characters, they will be recorded as having the same experiences/feelings about machine vision, and it is impossible to trace which tags belong to which characters.

**Comment by jilltxt** [comment]
@mareinna, maybe the ideal thing is to do this in the character node. We could add a section for each situation the character is in. So for instance:

> **[Mysterioso](https://machinevision.elmcip.net/content/mysterio)**
> 
> Race/ethnicity: White
> Gender: Male
> Species: Human
> Age: Adult
> 
> Situations this character appears in:
> [Spiderman: Far From Home (Drones)](https://machinevision.elmcip.net/content/spiderman-far-home-drones)
> Character OPERATES/VIEWS/IS VIEWED BY machine vision in this situation.
> Character sentiment: EMPOWERING; HELPFUL.
> Agency: Agency INCREASED by machine vision
> 
> Spiderman: Far from Home (Deep fakes)
> Spiderman: Far from Home (Augmented reality)

And then we COULD move all the sentiments and so on from the situation to the character. In some ways this might make it easier to do data analysis of the relationship between characters, gender, race etc and attitudes towards and positions in relation to machine vision. 

But it might also be more complicated than what we currently have, and would require redoing current situations. We would presumably want to heavily simplify the data we have for situations now.

**Comment by jilltxt** [comment]
Superceded by new situations hooray.
