### ISSUE TITLE
NEW DEFINITIONS THREAD

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#45]
We figured since we are under a time constraint and people are on and off holidays, it`s hard to get the group together. We are trying optimistically a new method where we can write suggestions (as comments).

Instructions: If you want to submit a your definition, write it as a comment and then tick the box for it to be revised and commented by the others in the group. Also this is a great thing to do even if you are just 2 or 3 in the office discussing.

**What characterizes the operator(s) of the machine vision technology in this situation?** 
- [ ] Not applicable
- [ ] An individual
- [ ] A targeted group
- [ ] Everyone
- [ ] Everything
- [ ] Actual user/player/reader/viewer of work is also the protagonist
- [ ] Customisable 

**Who owns/developed the technology:** 
- [ ]     AI
- [ ]     Individual
- [ ]     Collective
- [ ]     Corporation
- [ ]     Government
- [ ]     Military

**What is the machine vision doing in this specific situation?**
- [x] Analysing
- [x] Capturing
- [x] Comparing
- [x] Emoting
- [x] Generating
- [x] Identifying
- [x] Interpreting
- [x] Locating
- [x] Matching
- [x] Recording
- [x] Revealing
- [x] Targeting
- [x] Understanding

**How does the machine vision function in a larger (societal/institutional/interpersonal) context**
- [ ] Advising
- [ ] Controlling
- [ ] Deceiving
- [ ] Decorating/embellishing
- [ ] Inciting/provoking
- [ ] Informing/illustrating/demonstrating
- [ ] Inspiring/motivating
- [ ] Killing
- [ ] Oppressing
- [ ] Persuading
- [ ] Predicting
- [ ] Preventing
- [ ] Problem solving
- [ ] Remembering
- [ ] Replacing
- [ ] Subverting
- [ ] Transforming

**Relationships humans/machine vision**
- [ ] Binary subject/object relationship is problematic
- [ ] Cooperative
- [ ] Coopted
- [ ] Hierarchical
- [ ] No clear operator
- [ ] Oppositional
- [ ] There is an operator of the machine vision

**Comment by LinnHeidi** [comment]
Analysing:
_To differentiate or ascertain the elements of (something complex) in order to determine its structure or nature, and hence to explain or understand it_

Capturing:
_To represent, livestream, catch, or to document something._

Comparing:
_To mark or point out the similarities and differences of (two or more things)_

Emoting: 
_To express or communicate an emotion. E.g. an AI learning human emotion._

Generating:
_To bring into existence an object. Eg. such as a picture created by neural networks_

Recording (REMOVE)

Revealing:
_To disclose or make known (something previously unknown or kept secret)_

Targeting:
_To direct or aim on a course_

Understanding:
_To comprehend or to apprehend the meaning and to be thoroughly acquainted or familiar with the subject or object._

ADD Scanning?:
_To analyse by determining the nature and the form of an object or subject._

**Comment by jilltxt** [comment]
This is great, thanks for drafting this, @LinnHeidi! Very useful for starting our discussion! I'll just note the ones I think may need slightly different definitions.

**Capturing**: I like the definition Google pops up: "record accurately in words or pictures" - although words aren't relevant for us. Capturing is about simply recording something without analyzing it or doing anything more. I don't think livestreaming should be included in the definition, although live-streaming should be tagged as "capturing" (and perhaps also as something else, depending on the situation). I would also delete "represent" because it opens a can of worms (see a short summary of problems here: http://jilltxt.net/?p=4405 - basically it's used in cultural studies etc. to mean something constructed, not simply recorded). How about "**Capturing**: to record visual data, which may either be stored for future use or immediated used for another purpose." (We could maybe leave out the second part.)

**Emoting** - I think we should keep this to active expression of emotion - as in the machine vision technology is used to express emotion (as for instance with selfie lenses or with a robot that beams a heart onto a wall to express love). Emotion recognition is a different thing (understanding/learning/analysing) and could be tagged as "understanding" and/or "analyzing" depending on the situation.

**Targeting**: should probably include targeting an individual, like a drone that captures visual data and analyses it in order to identify an individual human target which it will then target/kill. 

**Understanding** Need to consider whether this is necessary in addition to analyzing.

**Scanning** I think scanning is too specific, and that capture and analyze work, depending on the situation. Also, "scanning" is often not used in the way defined here - e.g. "scan the document and send it by email" is pure capture, no analysis, and "she scans the landscape to try to spot the path onwards" uses scan as a human action of using vision to get a quick overview without details. 

Looking forwards to discussing :)

**Comment by LinnHeidi** [comment]
Should we have connecting?

**Comment by LinnHeidi** [comment]
Should we have hiding or deleting?

Eg jobber med å logge "Dirty Computer" og der sletter maskinsynet minner til hovudpersonen.

**Comment by LinnHeidi** [comment]
Should we have hiding or deleting?

Eg jobber med å logge "Dirty Computer" og der sletter maskinsynet minner til hovudpersonen.

**Comment by LinnHeidi** [comment]
I think maybe we should include "generating images" as a part of image generation? I am confused by this one, and want to use it beyond its definition.

**Comment by LindaKairus** [comment]
I would need a new tag in Who (or what) is viewed by the machine vision in this situation?:
I have specific objects that are viewed. I is not everything, or everyone.
I could use targeted group, but I always thought that is some kind of living/aware entities and not objects. Comments?
This is the case in most object recognition MV-situations.

**Comment by LindaKairus** [comment]
What is the machine vision doing in this specific situation?: 
I would suggest the tag Organizing (e.g. Jller)

**Comment by LindaKairus** [comment]
> I think maybe we should include "generating images" as a part of image generation? I am confused by this one, and want to use it beyond its definition.

As Linn Heidi I would also need to have a discussion how to tag especially images generated by neural networks, because I think we have quite a lot of them. It would be good to decide on a common practice how we read the works.

**Comment by LinnHeidi** [comment]
I don`t think this list is relevant anymore. 
We still need to update the topics list though. Maybe we can have a meeting about this soon! Would be nice to have that list ready before Solstrand? But I think we can close this one

**Comment by jilltxt** [comment]
OK, let's close this, but I'll make a new issue about updating topics and technologies definitions.
