### ISSUE TITLE
Decide how Machine POV should be defined and whether it's sufficient

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#65]
I added Machine POV (Machine Point of View) to the Aesthetics and Interface section. Is this what @ragsol was requesting? Does it work? When, exactly, do we use it? Do we need an additional question or a different one?

<img width="445" alt="Skjermbilde 2019-10-29 kl  11 31 53" src="https://user-images.githubusercontent.com/44365847/67759513-dda56b00-fa3f-11e9-8f9a-e57ad4c36eb3.png">

**Comment by jilltxt** [comment]
The current help text is: "Tick this box if the work directly shows us the machine vision's point of view. For instance, we may see "as though we are a drone" or "through a surveillance camera", or in a novel, we might read a description of what a robot sees focalised through the robot."  

In the meeting today, we agreed that Ragnhild will evaluate how this works and suggest changes/tweaks. Everyone will consider if it's clear for the kinds of sitations they are entering. 

Also, Jill made a view showing all of these: https://machine-vision.no/machinepov (the csv download currently doesn't work)

**Comment by ragsol** [comment]
It works for me. Two issues as I'm retagging now:
- 'Machine POV' for Just Dance is a bit tricky: we obviously see what the machine sees, but also a bunch of other things. (written elsewhere) While calibrating, you only see the motion tracking/body outline, so I guess I'd want to tag this.
- 'Machine POV' for Pokemon Go: I'd rather not tag this as MPOV, but I'm not sure why. In a way, we're just seeing the world 'the way its meant to', so there is no situated tech to view it from. However, we also see it through the cellphone, so I guess it's MPOV after all? O.o Edit: Actually, this goes for more AR, because the same issues pops up with Marcus and the NetHack View in WATCH_DOGS 2. For Marcus, the entire screen is 'taken over' by the AR view (as in Detroit, too), but I guess that also happens in PokGo? Perhaps we need to define if AR is MV or not? The shorter question is if it can be MPOV when it's third person.
- In 'Face your feelings', what you see is the same as the camera (like a mirror/Snapchat cam). Machine POV?

**Comment by jilltxt** [comment]
Perhaps we have to specify that by Machine POV we mean 
- first person
- not just an AR interface that is clearly intended to be helping a human viewer and is not representing the way a machine sees 

Argh, this is complicated. I think we need to work through some examples in a group? Or maybe just me and @ragsol since we seem to be the ones most interested in this?

**Comment by LinnHeidi** [comment]
We have come up with a solution, so we can close this issue now?

**Comment by jilltxt** [comment]
@ragsol, when you've written out the summary and help text, could you please post a link to them here (or copy and paste them here) and close the issue?

**Comment by ragsol** [comment]
Machine P.O.V.
Tick this box if the work directly shows us the machine vision's point of view, e.g. with grids, graininess, colors or similar features, often when the interface is an actual camera. This box changes _Colours_ and _Aesthetic characteristics_ from situation level to how the machine's actual vision is imagined. If you put on AR or night vision glasses and then suddenly the screen fills up with whatever you see through them, then that is machine P.O.V. Multiple monitors as in _Do Not Feed the Monkeys_ is not machine P.O.V. because the player character is clearly present. GAN generated artworks and AR are context dependent.

I guess the help text can be the first sentence?

**Comment by jilltxt** [comment]
Done.
