### ISSUE TITLE
Populate person title from first, middle and last name text fields

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#83]
ELMCIP have custom code that run when you add/edit a Person. It hides the node title and create it based on the current values of first, middle and last name.

## Custom

`function elmcip_setup_node_presave($node)` - https://github.com/elmcip/elmcip/blob/master/modules/elmcip_setup/elmcip_setup.module

**Comment by jilltxt** [comment]
This issue has become more urgent because after the upgrade, there is now a new Title field which is required - but we don't have a title. @steinmb: Can the title field be removed? If this is a lengthy coding job, should we just write in First name + Last name? We don't have THAT many persons in our database.

Here is what the screen looks like when you go to enter a new person:
![Screen Shot 2020-08-25 at 13 45 30](https://user-images.githubusercontent.com/44365847/91170502-46e62100-e6d9-11ea-8019-3fed2f8a3302.png)

What it looks like in my admin view:
![Screen Shot 2020-08-25 at 13 42 31](https://user-images.githubusercontent.com/44365847/91170465-35047e00-e6d9-11ea-861e-023dfe9f69ef.png)

**Comment by steinmb** [comment]
I'll port the Drupal 7 functionality of this to D9. I'll have a look tomorrow if that is OK. Should not be big job. The old code hide the title field in the form and uses first, middle, last -name to populate the title. Title is used just not by end user.

**Comment by steinmb** [comment]
Split out the code in https://github.com/elmcip/elmcip/issues/449 - Now all I have to do is port it.

**Comment by steinmb** [comment]
https://github.com/steinmb/elmcip_person is ported to Drupal 7 and 9 and included in our config.

```
composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 1 update, 0 removals
  - Updating steinmb/elmcip_person (1.0 => 1.1): Downloading (100%)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
```

Enabled the module and it is ready to be tested. I wrote a few official unit tests https://github.com/steinmb/elmcip_person/blob/8.x-dev/tests/src/Unit/PersonNameTest.php to make sure we catch all mutations of first, middle and last name and white spaces that users might introduce on pasting text into the form.

![Screenshot 2020-09-03 at 20 03 01](https://user-images.githubusercontent.com/683617/92151132-e5ccf480-ee20-11ea-92b5-ab99822c3376.png)

**Comment by jilltxt** [comment]
Looks great, thanks!
